# Generated by Django 4.2.25 on 2025-10-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alarm_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('device_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('system', 'System'), ('energy', 'Energia'), ('weather', 'Pogoda'), ('report', 'Raport')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Informacyjny'), ('warning', 'Ostrzeżenie'), ('critical', 'Krytyczny')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Otwarty'), ('acknowledged', 'Potwierdzony'), ('resolved', 'Zamknięty')], default='open', max_length=20)),
                ('is_quiet_hours', models.BooleanField(default=False)),
                ('notified', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('visible_for', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('both', 'Obaj')], default='both', max_length=10)),
            ],
        ),
    ]
