# Generated by Django 4.2.25 on 2025-12-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm_alert', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alert',
            new_name='alarm_alert_user_id_ce71f1_idx',
            old_name='alarm_alert_user_id_9a7f5c_idx',
        ),
        migrations.RenameIndex(
            model_name='alert',
            new_name='alarm_alert_severit_030fb2_idx',
            old_name='alarm_alert_severit_7d4e6a_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='alarm_alert_user_id_157fb6_idx',
            old_name='alarm_alert_user_id_8f8e8a_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='alarm_alert_sent_at_2254da_idx',
            old_name='alarm_alert_sent_at_4c5e7b_idx',
        ),
    ]
