# Generated by Django 4.2.25 on 2025-10-18 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('report_type', models.CharField(choices=[('COST', 'Cost Analysis'), ('PEAK', 'Peak Load'), ('OZE', 'OZE Production')], max_length=10, verbose_name='Report Type (Content)')),
                ('report_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=10, verbose_name='Report Frequency')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Date from')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Date to')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_timestamp'],
            },
        ),
    ]
