# Generated by Django 4.2.25 on 2025-10-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_reporting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='created_by',
        ),
        migrations.AddField(
            model_name='report',
            name='created_by_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Created by'),
        ),
    ]
