# Generated by Django 4.2.25 on 2025-12-08 21:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_reporting', '0002_remove_report_created_by_report_created_by_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('analysis_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('TRENDS', 'Trends'), ('PEAK', 'Peak'), ('ANOMALY', 'Anomaly')], max_length=20, verbose_name='Analysis Type')),
                ('analysis_title', models.CharField(max_length=200, verbose_name='Analysis Title')),
                ('analysis_summary', models.TextField(blank=True, null=True, verbose_name='Analysis Summary')),
                ('generate_chart', models.BooleanField(default=False, verbose_name='Generate Chart')),
            ],
            options={
                'verbose_name': 'Analysis',
                'verbose_name_plural': 'Analyses',
            },
        ),
        migrations.CreateModel(
            name='ReportCriteria',
            fields=[
                ('report_criteria_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('report_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom')], default='MONTHLY', max_length=10, verbose_name='Report Frequency')),
                ('date_created_from', models.DateField(blank=True, null=True, verbose_name='Date from')),
                ('date_created_to', models.DateField(blank=True, null=True, verbose_name='Date to')),
                ('device_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Device Type')),
            ],
            options={
                'verbose_name': 'Report Criteria',
                'verbose_name_plural': 'Report Criteria',
            },
        ),
        migrations.RemoveField(
            model_name='report',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='report',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='report',
            name='id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_frequency',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
        migrations.AddField(
            model_name='report',
            name='data_for_analysis',
            field=models.JSONField(blank=True, default=dict, verbose_name='Data for Analysis'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_description',
            field=models.TextField(blank=True, null=True, verbose_name='Report Description'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Visualization',
            fields=[
                ('visualization_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chart_title', models.CharField(max_length=200, verbose_name='Chart Title')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='File Path')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to='analysis_reporting.analysis', verbose_name='Analysis')),
            ],
            options={
                'verbose_name': 'Visualization',
                'verbose_name_plural': 'Visualizations',
            },
        ),
        migrations.CreateModel(
            name='ReportCompare',
            fields=[
                ('report_compare_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by_id', models.IntegerField(blank=True, null=True, verbose_name='Created by')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('compare_description', models.TextField(blank=True, null=True, verbose_name='Compare Description')),
                ('report_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_one', to='analysis_reporting.report', verbose_name='Report One')),
                ('report_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_two', to='analysis_reporting.report', verbose_name='Report Two')),
            ],
            options={
                'verbose_name': 'Report Compare',
                'verbose_name_plural': 'Report Comparisons',
                'ordering': ['-created_timestamp'],
            },
        ),
        migrations.AddField(
            model_name='analysis',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analysis_reporting.report', verbose_name='Report'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_criteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='analysis_reporting.reportcriteria', verbose_name='Report Criteria'),
        ),
    ]
