# Generated by Django 4.2.25 on 2025-12-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_reporting', '0003_analysis_reportcriteria_remove_report_date_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcompare',
            name='visualization_file',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Visualization File Path'),
        ),
    ]
