# Generated by Django 4.2.25 on 2025-12-08 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_reporting', '0004_reportcompare_visualization_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcompare',
            name='visualization_file',
        ),
    ]
