# Generated by Django 4.2.25 on 2025-12-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_reporting', '0006_reportcompare_visualization_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='has_anomaly',
            field=models.BooleanField(default=False, verbose_name='Has Anomaly Detected'),
        ),
    ]
