# Generated by Django 4.2.25 on 2025-10-25 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_id', models.IntegerField()),
                ('user_id', models.TextField()),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('working_period', models.TimeField()),
                ('power_consumption', models.FloatField()),
                ('working_status', models.BooleanField(default=False)),  
            ],
        ),
    ]
