# Generated by Django 4.2.25 on 2025-10-25 16:39

from django.db import migrations
from communication.utils.fill_data import fill_schedules

class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
        ('data_acquisition', '0001_initial'),  # Dodano zależność od data_acquisition
    ]

    operations = [
        migrations.RunPython(fill_schedules)
    ]
