# Generated by Django 4.2.25 on 2025-12-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privacy_policy_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='code',
            name='purpose',
            field=models.CharField(choices=[('RESET_PASSWORD', 'Reset Password'), ('CREATE_GROUP', 'Create Group'), ('TWO_FACTOR', 'Two Factor Auth')], default='RESET_PASSWORD', max_length=20),
        ),
    ]
