# Generated by Django 4.2.25 on 2025-12-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_user_privacy_policy_accepted_user_terms_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('spectator', 'Spectator')], default='admin', max_length=20),
        ),
    ]
