# Generated by Django 4.2.25 on 2026-01-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_alter_code_purpose_groupinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='purpose',
            field=models.CharField(choices=[('RESET_PASSWORD', 'Reset Password'), ('CREATE_GROUP', 'Create Group'), ('TWO_FACTOR', 'Two Factor Auth')], default='RESET_PASSWORD', max_length=20),
        ),
        migrations.DeleteModel(
            name='GroupInvitation',
        ),
    ]
