# Generated by Django 4.2.25 on 2025-10-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('power', models.FloatField()),
                ('worktime', models.IntegerField()),
                ('current_hours', models.CharField(default='00:00', max_length=10)),
                ('priority', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('is_temp', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'optimization_control_device',
            },
        ),
    ]
