# Generated by Django 4.2.25 on 2025-10-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('power', models.FloatField()),
                ('worktime', models.IntegerField()),
                ('current_cost', models.FloatField()),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
