# Generated by Django 4.2.25 on 2025-12-11 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimization_control', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
