# Generated by Django 4.2.25 on 2025-10-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimDevice',
            fields=[
                ('device_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('type_code', models.CharField(choices=[('pv', 'pv'), ('wind', 'wind'), ('hp', 'hp'), ('other', 'other')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('disabled', 'disabled')], default='active', max_length=10)),
                ('power_kw', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('pv_kwp', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('wind_rated_kw', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('hp_t_in_set_c', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
