# Generated by Django 4.2.25 on 2025-12-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0005_generationhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_capacity_kwh', models.DecimalField(decimal_places=3, default=100, max_digits=12)),
                ('current_charge_kwh', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('last_randomized_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
