# Generated by Django 4.2.25 on 2025-12-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0006_batterystate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('charge_kwh', models.DecimalField(decimal_places=3, max_digits=12)),
                ('source', models.CharField(default='system', max_length=50)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
