# Generated by Django 4.2.25 on 2025-11-13 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, help_text='Unikalny identyfikator urządzenia (np. numer seryjny)', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, help_text='Przyjazna dla użytkownika nazwa', max_length=100)),
                ('device_type', models.CharField(db_index=True, max_length=50)),
                ('location', models.CharField(blank=True, help_text='Główna lokalizacja urządzenia', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Czy urządzenie jest aktywne')),
            ],
            options={
                'ordering': ['name', 'device_id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('device_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('metric', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('signal_dbm', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=50)),
                ('device', models.ForeignKey(help_text='Urządzenie, z którego pochodzi ten odczyt', on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='data_acquisition.device')),
            ],
        ),
    ]
