# Generated by Django 5.2.7 on 2025-10-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('device_id', models.CharField(max_length=50)),
                ('device_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('metric', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
