# Generated by Django 4.2.25 on 2025-12-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_acquisition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicereading',
            name='priority',
            field=models.IntegerField(default=1, help_text='Priorytet odczytu'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.IntegerField(db_index=True, help_text='Unikalny identyfikator urządzenia', unique=True),
        ),
        migrations.AlterField(
            model_name='devicereading',
            name='status',
            field=models.BooleanField(default=True, help_text='Status urządzenia (True/False'),
        ),
    ]
