# Generated by Django 4.2.25 on 2025-10-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_acquisition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicereading',
            name='signal_dbm',
            field=models.IntegerField(default=0),
        ),
    ]
