# Generated by Django 4.2.25 on 2025-12-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_acquisition', '0002_devicereading_priority_alter_device_device_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='id',
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.IntegerField(db_index=True, help_text='Unikalny identyfikator urządzenia', primary_key=True, serialize=False),
        ),
    ]
