# Generated by Django 4.2.25 on 2025-12-11 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_acquisition', '0003_remove_device_id_alter_device_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicereading',
            name='priority',
        ),
        migrations.AddField(
            model_name='device',
            name='priority',
            field=models.IntegerField(default=0, help_text='Priorytet urządzenia (0-2)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
